// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAJm4fCd9sjBUmjkugIX7dMxKvVbkxSzY',
    appId: '1:859810577382:web:f7ab2ba306c13593e0b427',
    messagingSenderId: '859810577382',
    projectId: 'health-78057',
    authDomain: 'health-78057.firebaseapp.com',
    storageBucket: 'health-78057.appspot.com',
    measurementId: 'G-LHXCQMG28K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA44-GujjpAfNGouL0CepefvYg-yiAyhfY',
    appId: '1:859810577382:android:3b6e32f11df1a77ce0b427',
    messagingSenderId: '859810577382',
    projectId: 'health-78057',
    storageBucket: 'health-78057.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByddymS-Jgdsr-0LL4ehLaDDq3chPnJvI',
    appId: '1:859810577382:ios:04e36d575ab413aae0b427',
    messagingSenderId: '859810577382',
    projectId: 'health-78057',
    storageBucket: 'health-78057.appspot.com',
    iosBundleId: 'com.alfortius.health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByddymS-Jgdsr-0LL4ehLaDDq3chPnJvI',
    appId: '1:859810577382:ios:92912b7a5fbef604e0b427',
    messagingSenderId: '859810577382',
    projectId: 'health-78057',
    storageBucket: 'health-78057.appspot.com',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAJm4fCd9sjBUmjkugIX7dMxKvVbkxSzY',
    appId: '1:859810577382:web:ef21b09c5f36d3a7e0b427',
    messagingSenderId: '859810577382',
    projectId: 'health-78057',
    authDomain: 'health-78057.firebaseapp.com',
    storageBucket: 'health-78057.appspot.com',
    measurementId: 'G-KQFQ4PYL3M',
  );
}
